window.SECTOR_TAXONOMY = {
  "acero_metalmecanica": {
    "name": "Acero & Metalmecánica",
    "keywords": [
      "acero estructural",
      "acero de refuerzo",
      "perfiles de acero",
      "vigas de acero",
      "tubería de acero",
      "tuberia de acero",
      "tubería estructural",
      "tuberia estructural",
      "varilla",
      "varillas",
      "varilla de acero",
      "cubierta metálica",
      "cubiertas metálicas",
      "estructura metálica",
      "estructuras metálicas",
      "estructura metalica",
      "estructuras metalicas",
      "vigas",
      "perfilería",
      "perfiles",
      "lámina galvanizada",
      "lamina galvanizada",
      "cercha",
      "cerchas",
      "puente metálico",
      "puente vehicular",
      "reforzamiento estructural",
      "soldadura",
      "hierro figurado",
      "carpintería metálica",
      "cerramientos metálicos",
      "malla eslabonada",
      "acero figurado",
      "acero inoxidable",
      "suministro de acero"
    ]
  },
  "horeca_industrial": {
    "name": "HORECA & Maquinaria Gastronómica",
    "keywords": [
      "cocina industrial",
      "cocinas industriales",
      "horno combinado",
      "hornos industriales",
      "cuarto frío",
      "cuartos fríos",
      "cuartos frios",
      "refrigeración comercial",
      "refrigeracion comercial",
      "estufa industrial",
      "estufas industriales",
      "campana extractora",
      "campanas extractoras",
      "marmita",
      "marmitas",
      "lavavajillas industrial",
      "menaje institucional",
      "dotación de restaurante",
      "dotacion de restaurante",
      "alimentación escolar",
      "pae",
      "planta de procesamiento",
      "congelador industrial",
      "equipamiento gastronómico",
      "equipamiento gastronomico",
      "acero inoxidable 304",
      "autoservicio de alimentos"
    ]
  },
  "energia_solar_alumbrado": {
    "name": "Energía Solar & Alumbrado Público",
    "keywords": [
      "energía solar",
      "energia solar",
      "panel solar",
      "paneles solares",
      "sistema fotovoltaico",
      "sistemas fotovoltaicos",
      "fotovoltaica",
      "fotovoltaico",
      "energía renovable",
      "energia renovable",
      "luminarias led",
      "luminaria led",
      "alumbrado público",
      "alumbrado publico",
      "subestación eléctrica",
      "subestacion electrica",
      "redes eléctricas",
      "redes electricas",
      "transformador",
      "transformadores",
      "inversor solar",
      "baterías solares",
      "baterias solares",
      "eficiencia energética"
    ]
  },
  "obra_civil_general": {
    "name": "Construcción & Obra Civil General",
    "keywords": [
      "obra civil",
      "obras civiles",
      "adecuación de infraestructura",
      "adecuacion de infraestructura",
      "construcción de sede",
      "construccion de sede",
      "edificación",
      "edificacion",
      "pavimentación",
      "mantenimiento de vías",
      "hospital",
      "colegio",
      "escuela",
      "escenarios deportivos",
      "parque"
    ]
  }
};
