window.SECTOR_TAXONOMY = {
  "acero_metalmecanica": {
    "name": "Acero & Metalmecánica",
    "grupo": "suministros_equipos",
    "keywords": [
      "acero estructural",
      "acero de refuerzo",
      "perfiles de acero",
      "vigas de acero",
      "tubería de acero",
      "tuberia de acero",
      "tubería estructural",
      "tuberia estructural",
      "varilla",
      "varillas",
      "varilla de acero",
      "cubierta metálica",
      "cubiertas metálicas",
      "estructura metálica",
      "estructuras metálicas",
      "estructura metalica",
      "estructuras metalicas",
      "vigas",
      "perfilería",
      "perfiles",
      "lámina galvanizada",
      "lamina galvanizada",
      "cercha",
      "cerchas",
      "puente metálico",
      "puente vehicular",
      "reforzamiento estructural",
      "soldadura",
      "hierro figurado",
      "carpintería metálica",
      "cerramientos metálicos",
      "malla eslabonada",
      "acero figurado",
      "acero inoxidable",
      "suministro de acero"
    ]
  },
  "horeca_industrial": {
    "name": "HORECA & Maquinaria Gastronómica",
    "grupo": "suministros_equipos",
    "keywords": [
      "cocina industrial",
      "cocinas industriales",
      "horno combinado",
      "hornos industriales",
      "cuarto frío",
      "cuartos fríos",
      "cuartos frios",
      "refrigeración comercial",
      "refrigeracion comercial",
      "estufa industrial",
      "estufas industriales",
      "campana extractora",
      "campanas extractoras",
      "marmita",
      "marmitas",
      "lavavajillas industrial",
      "menaje institucional",
      "dotación de restaurante",
      "dotacion de restaurante",
      "planta de procesamiento",
      "congelador industrial",
      "equipamiento gastronómico",
      "equipamiento gastronomico",
      "acero inoxidable 304",
      "autoservicio de alimentos"
    ]
  },
  "alimentacion_escolar": {
    "name": "Alimentación Escolar (PAE)",
    "grupo": "servicios",
    "keywords": [
      "pae",
      "alimentación escolar",
      "alimentacion escolar",
      "complemento alimentario",
      "complementos alimentarios",
      "restaurante escolar",
      "restaurantes escolares",
      "ración industrializada",
      "racion industrializada",
      "ración preparada en sitio",
      "racion preparada en sitio"
    ]
  },
  "energia_solar_alumbrado": {
    "name": "Energía Solar & Alumbrado Público",
    "grupo": "obra_infraestructura",
    "keywords": [
      "energía solar",
      "energia solar",
      "panel solar",
      "paneles solares",
      "sistema fotovoltaico",
      "sistemas fotovoltaicos",
      "fotovoltaica",
      "fotovoltaico",
      "energía renovable",
      "energia renovable",
      "luminarias led",
      "luminaria led",
      "alumbrado público",
      "alumbrado publico",
      "subestación eléctrica",
      "subestacion electrica",
      "redes eléctricas",
      "redes electricas",
      "transformador",
      "transformadores",
      "inversor solar",
      "baterías solares",
      "baterias solares",
      "eficiencia energética"
    ]
  },
  "obra_civil_general": {
    "name": "Construcción & Obra Civil General",
    "grupo": "obra_infraestructura",
    "keywords": [
      "obra civil",
      "obras civiles",
      "adecuación de infraestructura",
      "adecuacion de infraestructura",
      "construcción de sede",
      "construccion de sede",
      "edificación",
      "edificacion",
      "pavimentación",
      "pavimentacion",
      "mantenimiento de vías",
      "mantenimiento de vias",
      "escenarios deportivos",
      "malla vial",
      "mejoramiento de vía",
      "mejoramiento de via",
      "mejoramiento de vías",
      "mejoramiento de vias",
      "mejoramiento de la vía",
      "mejoramiento de la via",
      "vía terciaria",
      "via terciaria",
      "vías terciarias",
      "vias terciarias",
      "placa huella",
      "pavimento rígido",
      "pavimento rigido",
      "pavimento flexible",
      "infraestructura educativa",
      "obras complementarias",
      "infraestructura física",
      "infraestructura fisica"
    ]
  },
  "agua_saneamiento": {
    "name": "Agua Potable & Saneamiento",
    "grupo": "obra_infraestructura",
    "keywords": [
      "agua potable",
      "aguas residuales",
      "ptap",
      "ptar",
      "acueducto",
      "acueductos",
      "alcantarillado",
      "alcantarillados",
      "planta de tratamiento",
      "plantas de tratamiento",
      "saneamiento básico",
      "saneamiento basico",
      "tratamiento de aguas"
    ]
  },
  "tecnologia": {
    "name": "Tecnología & Equipos de Cómputo",
    "grupo": "suministros_equipos",
    "keywords": [
      "equipos de cómputo",
      "equipos de computo",
      "equipo de cómputo",
      "equipo de computo",
      "computadores",
      "infraestructura tecnológica",
      "infraestructura tecnologica",
      "equipos tecnológicos",
      "equipos tecnologicos",
      "licenciamiento",
      "licencias de software",
      "software",
      "seguridad perimetral",
      "centro de datos",
      "cableado estructurado",
      "redes de datos"
    ]
  },
  "interventoria_consultoria": {
    "name": "Interventoría & Consultoría",
    "grupo": "servicios",
    "keywords": [
      "interventoría técnica",
      "interventoria tecnica",
      "interventoría integral",
      "interventoria integral",
      "interventoría administrativa",
      "interventoria administrativa",
      "estudios y diseños",
      "estudios y disenos",
      "consultoría especializada",
      "consultoria especializada"
    ]
  }
};
window.SECTOR_GROUPS = [
  {
    "id": "obra_infraestructura",
    "name": "Obra e infraestructura"
  },
  {
    "id": "suministros_equipos",
    "name": "Suministros y equipos"
  },
  {
    "id": "servicios",
    "name": "Servicios"
  }
];
